#!/bin/bash

WATCH_DIR="/srv/cowrie/var/lib/cowrie/tty"
SCRIPT="/opt/honeypot/honeypot_alert.py"

inotifywait -m -e create "$WATCH_DIR" | while read path action file; do
    echo "New file detected: $file"
    python3 "$SCRIPT"
done
